x-api: &api
  build: ./
  env_file: .env
  environment:
    POSTGRES_HOST: db

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    <<: *api
    depends_on:
      - db
    command: "python -m alembic upgrade head"

  backend:
    <<: *api
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - migrations
    command: "python -m uvicorn store.main:fastapi_app --factory --host 0.0.0.0"

volumes:
  postgres-data:
