x-api: &api
  build: ./
  env_file: .env
  environment:
    POSTGRES_HOST: db

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    <<: *api
    depends_on:
      - db
    command: "python -m alembic upgrade head"

  backend:
    <<: *api
    depends_on:
      - migrations
    command: "python -m app.main"

volumes:
  postgres-data:
